import {
  boolean,
  integer,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

// Enums
export const winnerSelectionEnum = pgEnum('winner_selection', [
  'random',
  'number',
])

// Users table
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  password: varchar('password', { length: 255 }).notNull(),
  nickname: varchar('nickname', { length: 255 }),
  active: boolean('active').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// Assets table (polymorphic)
export const assets = pgTable('assets', {
  id: serial('id').primaryKey(),
  modelType: varchar('model_type', { length: 50 }).notNull(), // 'drawing' or 'participant'
  modelId: varchar('model_id', { length: 255 }).notNull(), // drawing.id or participant.id
  url: text('url').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// Participants table
export const participants = pgTable('participants', {
  id: serial('id').primaryKey(),
  drawingId: varchar('drawing_id', { length: 255 })
    .notNull()
    .references(() => drawings.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull(),
  email: varchar('email', { length: 255 }),
  phone: varchar('phone', { length: 50 }).notNull(),
  selectedNumber: integer('selected_number'), // The number chosen by participant (if applicable)
  isEligible: boolean('is_eligible'), // null = pending, true = approved, false = rejected
  paymentCaptureId: integer('payment_capture_id').references(() => assets.id), // Reference to payment proof asset
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// Drawing table
export const drawings = pgTable('drawings', {
  id: varchar('id', { length: 255 }).primaryKey(), // Generated by server, used for sharing
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  title: varchar('title', { length: 255 }).notNull(),
  guidelines: text('guidelines').array(), // Array of text for guidelines/requirements
  isPaid: boolean('is_paid').notNull().default(false),
  price: integer('price').default(0), // Price in cents to avoid decimal issues
  winnerSelection: winnerSelectionEnum('winner_selection').notNull(),
  quantityOfNumbers: integer('quantity_of_numbers').notNull().default(0),
  isWinnerNumberRandom: boolean('is_winner_number_random').default(true), // true = random, false = manual entry
  winnerNumber: integer('winner_number'), // The actual winning number (set manually or by system)
  winnerId: integer('winner_id'), // Reference to participant who won
  endAt: timestamp('end_at').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  drawings: many(drawings),
}))

export const drawingsRelations = relations(drawings, ({ one, many }) => ({
  user: one(users, {
    fields: [drawings.userId],
    references: [users.id],
  }),
  participants: many(participants),
  winner: one(participants, {
    fields: [drawings.winnerId],
    references: [participants.id],
  }),
}))

export const participantsRelations = relations(participants, ({ one }) => ({
  drawing: one(drawings, {
    fields: [participants.drawingId],
    references: [drawings.id],
  }),
  paymentCapture: one(assets, {
    fields: [participants.paymentCaptureId],
    references: [assets.id],
  }),
}))

// Copilot: do Not delete this
export const todos = pgTable('todos', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})
